---
# tasks file for kube-master
- name: Installing docker
  package:
          name: docker
          state: present

- name: Start docker service
  service:
          name: docker
          state: started
          enabled: yes

- name: Kubernetes repo alternate
  shell: |
          cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
          [kubernetes]
          name=Kubernetes
          baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
          exclude=kubelet kubeadm kubectl
          EOF



- name: Installing softwares
  yum:
          name: "{{ item }}"
          state: present
          disable_excludes: kubernetes
  loop:
          - kubectl
          - kubeadm
          - kubelet

- name: Start and enable kubelet services
  service:
          name: kubelet
          state: started
          enabled: yes

- name: pull config images
  command: kubeadm config images pull

- name: initialise cidr
  shell: kubeadm init --pod-network-cidr={{ cidr }} --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem 

- name: change docker configuration
  file:
    src: daemon.json
    dest: etc/docker/daemon.json


- name: restart docker
  service:
          name: docker
          state: restarted

- name: make routing policy
  copy:
          src: k8s.conf
          dest: /etc/sysctl.d/k8s.conf

- name: enable system
  shell: "sysctl --system"

- name: Install ip-route tc
  package:
          name: iproute-tc
          state: present

- name: start the master
  shell: "kubeadm init --pod-network-cidr={{ cidr }} --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem"
  ignore_errors: True

- name: config file setup
  shell: |
          mkdir -p $HOME/.kube
          sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
          sudo chown $(id -u):$(id -g) $HOME/.kube/config

- name: free some RAM caches
  shell: "echo 3 > /proc/sys/vm/drop_caches"

- name: apply CNI plugins
  shell: "kubectl apply  -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"

- name: Get join token
  command: "kubeadm token create --print-join-command"
  register: x
  ignore_errors: True

- name: "Storing tokens"
  local_action: copy content={{ x.stdout }} dest=/tmp/token

- name: join token
  debug:
          var: x

